main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('donate/', views.donate, name='donate')
]

ppw_kel_12/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('donations/', include('daftarDonasi.urls')),
    path('reportIssue/', include('report.urls')),
    path('question/', include('pertanyaan.urls')),
    path('testi/', include('testi.urls')),
    path('institution/', include('donasi.urls')),
    path('userauth/', include('userauth.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testi/urls.py
from django.urls import path, include
from . import views
app_name = 'testi'

urlpatterns = [
    path('', views.tampilan, name='tampilan'),
    path('atur/', views.testi, name='testi'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('searchh', views.searchh,name="searchh"),
    path('all', views.name_list, name="list-nama"),
]

userauth/urls.py
from django.urls import path
from .views import user_login,user_logout

urlpatterns = [
	path('login/', user_login, name = 'login'),
    path('logout/', user_logout, name = 'logout'),
]

app_name = 'userauth'

testi/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Testi(models.Model):
    nama = models.CharField(max_length = 100)
    institusi=models.CharField(max_length=100)
    testimoni = models.TextField(max_length = 1000)
    tanggal_testi = models.DateField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['institusi','nama']),
            models.Index(fields=['nama'], name='nama_idx'),
        ]
    def __str__(self):
        return self.nama

testi/forms.py
from django import forms
from .models import Testi
# Create your views here.

class Testimoni_Form(forms.ModelForm):
    class Meta:
        model = Testi
        fields = [
            'nama',
            'institusi',
            'testimoni'
        ]
        widgets = {
            'nama': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Name'
				}
			),
            'institusi': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Institution'
				}
			),
            'testimoni': forms.TextInput(
				attrs = {
					'class': 'form-control',
					'placeholder': 'Testimonial',
                    'height':400 
				}
			)
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

testi/views.py
from django.shortcuts import render, redirect
from .forms import Testimoni_Form
from .models import Testi
from django.contrib.auth.models import User

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .serializers import TestiSerializer

def tampilan(request):
    testi = Testi.objects.all()
    context = {
        'semua_testi':testi
    }
    return render(request, 'tampilanTesti.html', context)

def testi(request):
    if request.user.is_authenticated:
        testi_form = Testimoni_Form(request.POST or None)
        if request.method == "POST":
            if testi_form.is_valid():
                testi_form.save()

            return redirect('testi:tampilan')
        
        context = {
            'testi_form' : testi_form
        }
        return render(request, 'isiTesti.html', context)
    else:
        return redirect('userauth:login')

def delete(request, delete_id):
    Testi.objects.filter(id = delete_id).delete()
    return redirect('testi:tampilan')

def searchh(request):
    testi = Testi.objects.all()
    context = {
        'semua_testi':testi
    }
    return render(request, 'testimonee.html', context)
 


@csrf_exempt
def name_list(request) :
    try :
        arguments = request.GET['q']
    except :
        arguments = ""

    if request.method == "GET" :
        institusi = Testi.objects.filter(institusi__icontains=arguments)
        serializer = TestiSerializer(institusi, many=True)
        return JsonResponse(serializer.data, safe=False)





 

testi/templates/isiTesti.html
{% extends 'base.html' %} {% block content%}
<h1 style="color: #4B6574; font-weight: bold; padding-left: 10%; padding-top: 5%;">Give Us Testimonial
</h1>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="id_nama">Name:*</label> {{testi_form.nama}}
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="id_institusi">Institution:*</label> {{testi_form.institusi}}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="id_testimoni">Testimonial:</label> {{testi_form.testimoni}}
        </div>

        <button type="submit" class="btn btn-light">Submit</button>
        <a href="{% url 'testi:tampilan' %}" style="color: black;"> See All </a>
    </form>
</div>
{% endblock %}

testi/templates/tampilanTesti.html
 {% extends 'base.html' %} {% block content%}{% load static %}
<!DOCTYPE html>
<html>

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        html,
        body,
        .Container {
            height: 100%;
        }
        
        .Container:before {
            content: '';
            height: 100%;
            float: right;
        }
        
        .Footer {
            margin-bottom: 10px;
            background-color: #91b14c;
        }
        
        .Content {
            position: relative;
            z-index: 1;
        }
        
        .Content:after {
            content: '';
            clear: both;
            display: block;
        }
        
        .Wrapper {
            position: absolute;
            width: 100%;
            height: 100%;
        }
        
        .Wrapper>div {
            height: 100%;
        }
        
        .RightContent {
            overflow: hidden;
        }
        
        .RightContent:hover {
            overflow: auto;
        }
        
        .LeftContent {
            float: left;
            width: 50%;
        }
        
        div.card-header.text-center {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
        
        .card-header {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        
        a {
            text-decoration: none;
        }
        
        .sapaan {
            text-align: center;
            padding-top: 2rem;
            padding-bottom: 1rem;
        }
        
        .isi-page {
            margin: 2rem;
            margin-bottom: 0;
        }
        
        .row {
            margin: 0;
        }
        
        .text-muted {
            margin-left: 2rem;
        }
        
        .accordion {
            background-color: #eee;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
        }
        
        .active,
        .accordion:hover {
            background-color: #ccc;
        }
        
        .accordion:after {
            content: '\002B';
            color: #777;
            font-weight: bold;
            float: right;
            margin-left: 5px;
        }
        
        .active:after {
            content: "\2212";
        }
        
        .panel {
            padding: 0 18px;
            background-color: white;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
        }
        
        body {
            background-color: white;
            color: black;
        }
        
        #acr1 {
            order: 1;
        }
        
        #acr2 {
            order: 2;
        }
        
        #acr3 {
            order: 3;
        }
        
        #acr4 {
            order: 4;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>
        $(function() {

            console.log($(window))
            $(".search-box").keyup(function() {
                var element = $(".search-box").val()

                $.ajax({
                    url: '/testi/all?q=' + element,
                    success: function(e) {
                        $(".content").empty();

                        if (e.length != 0) {
                            for (i = 0; i < e.length; i++) {
                                $(".content").append(`
                        <div class="row align-items-center">
                            <p>` + e[i].nama + `</p><br>
                            
                        </div>
                        <hr style="margin-left: 5%; margin-right: 5%; margin-top: 0;">
                        `)
                            }
                        } else {
                            $(".content").append(`
                    <div class="row align-items-center justify-content-center" style="margin: 5%;">
                        <h1>There are no testimoni</h1>
                    </div>
                    `)
                        }
                    }
                })
            })
        });
    </script>
    <script src="{% static 'main.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body style="background-color: #e4f5e2;">
    <div class="Container">
        <div class="Content">
            <div class="Wrapper">
                <div class="LeftContent" style="padding-left: 10%;padding-top: 5%;">
                    <b><h1 style="color: #4B6574; font-weight: bold; ">
                        What Do<br>People Say<br>About Us?
                    </h1></b> {% if user.is_authenticated %}
                    <a style="margin-bottom: 30px;" href="{% url 'testi:testi' %}" class="btn btn-light">Give Us Testimoni</a> {%else%}
                    <p style="color: red;">*login required</p>
                    <a style="margin-bottom: 30px;" href="{% url 'userauth:login' %}" class="btn btn-light">Give Us Testimoni</a> {%endif%}
                </div>
                <div class="RightContent" style="padding-top: 2.5%;padding-right: 2.5%; ">
                    {% if user.is_authenticated %}
                    <a style="margin-bottom: 30px;" href="{% url 'testi:searchh' %}" class="btn btn-light">Click here to search </a> {%else%}
                    <p style="color: red;">*login required</p>
                    <a style="margin-bottom: 30px;" href="{% url 'userauth:login' %}" class="btn btn-light">Click here to search </a> {%endif%} {% if user.is_authenticated %}
                    <p>(Click to detail)</p>
                    <div class=content>
                        {% for itu in semua_testi %}
                        <div class="isi-page">
                            <div class="element">
                                <button class="accordion" id="acr1">
                            <h3>
                                <center><b>{{itu.nama}}</b>, <u>{{itu.institusi}}</u></center>
                            </h3></button>
                                <div class="panel" id="tab1">
                                    <dl class="row card-body">
                                        <center>
                                            <p>{{itu.testimoni}}</p>
                                        </center><br><br><br>
                                        <p style="text-align: right;">{{itu.tanggal_testi}}</p>

                                        <a href="{% url 'testi:delete' itu.id %}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Hapus">
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"></path>
                                            </svg>
                                        </a>
                                    </dl>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {%else%}
                    <p style="color: red;">*login to see full testimoni</p>
                    <div class=content>
                        {% for itu in semua_testi %}
                        <div class="isi-page">
                            <div class="element">
                                <button class="accordion" id="acr1">
                            <h3>
                                <center><b>***</b>, <u>{{itu.institusi}}</u></center>
                            </h3></button>
                                <div class="panel" id="tab1">
                                    <dl class="row card-body">
                                        <center>
                                            <p style="text-align: center; ">{{itu.testimoni}}</p>
                                        </center><br><br><br>
                                        <p style="text-align: right;"><br><br><br>time:????</p>
                                    </dl>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>


    <div class="Footer"><br><br></div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>


</body>

</html>
{% endblock %}

testi/templates/testimonee.html
{% extends 'base.html' %} {% block content%}{% load static %}

<head>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        
        html,
        body,
        .Container {
            height: 100%;
        }
        
        .Container:before {
            content: '';
            height: 100%;
            float: right;
        }
        
        .Footer {
            margin-bottom: 10px;
            background-color: #91b14c;
        }
        
        .Content {
            position: relative;
            z-index: 1;
        }
        
        .Content:after {
            content: '';
            clear: both;
            display: block;
        }
        
        .Wrapper {
            position: absolute;
            width: 100%;
            height: 100%;
        }
        
        .Wrapper>div {
            height: 100%;
        }
        
        .RightContent {
            overflow: hidden;
        }
        
        .RightContent:hover {
            overflow: auto;
        }
        
        .LeftContent {
            float: left;
            width: 50%;
        }
        
        div.card-header.text-center {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
        
        .card-header {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        
        a {
            text-decoration: none;
        }
        
        .sapaan {
            text-align: center;
            padding-top: 2rem;
            padding-bottom: 1rem;
        }
        
        .isi-page {
            margin: 2rem;
            margin-bottom: 0;
        }
        
        .row {
            margin: 0;
        }
        
        .text-muted {
            margin-left: 2rem;
        }
        
        .accordion {
            background-color: #eee;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
        }
        
        .active,
        .accordion:hover {
            background-color: #ccc;
        }
        
        .accordion:after {
            content: '\002B';
            color: #777;
            font-weight: bold;
            float: right;
            margin-left: 5px;
        }
        
        .active:after {
            content: "\2212";
        }
        
        .panel {
            padding: 0 18px;
            background-color: white;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>
        $(function() {

            console.log($(window))
            $(".search-box").keyup(function() {
                var element = $(".search-box").val()

                $.ajax({
                    url: '/testi/all?q=' + element,
                    success: function(e) {
                        $(".content").empty();

                        if (e.length != 0) {
                            for (i = 0; i < e.length; i++) {
                                $(".content").append(`<div class="isi-page">
        <div class="element">

            <h3>
                <center><b>` + e[i].nama + `</b>, <u>` + e[i].institusi + `</div></u></center>
            </h3>
    </div>
                            
                        
                        `)
                            }
                        } else {
                            $(".content").append(`
                    <div class="row align-items-center justify-content-center" style="margin: 5%;">
                        <h1>There are no testimoni</h1>
                    </div>
                    `)
                        }
                    }
                })
            })
        });
    </script>
    <script src="{% static 'main.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<p>search testimonee by institution</p>
<div class="input-group col-md-3">
    <span class="input-group-append">
    <input class="search-box form-control py-2" type="search" placeholder="Search..." id="example-search-input" name="search">
    </span>
</div>
<div class=content>
    {% for itu in semua_testi %}
    <div class="isi-page">
        <div class="element">

            <h3>
                <center><b>{{itu.nama}}</b>, <u>{{itu.institusi}}</u></center>
            </h3>
            <div class="panel" id="tab1">
                <dl class="row card-body">
                    <center>
                        <p style="text-align: right;">{{itu.tanggal_testi}}</p>
                    </center>
                    <a href="{% url 'testi:delete' itu.id %}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Hapus">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"></path>
                    </svg>
                    </a>
                </dl>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<a style="margin-bottom: 30px;" href="{% url 'testi:tampilan' %}" class="btn btn-light">back </a>{% endblock %}